### ISSUE TITLE
validate provides incorrect explanation link

### ISSUE THREAD

**Issue by iamwyza** [zapier/zapier-platform#108]
### Bug Description

When validating a CLI project, if there is a warning/error/etc, it provides some information that includes a link to the schema for the issue.  The link is incorrect and leads to a 404.

### Reproduction Steps
```
 zapier validate

Validating project locally.
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ = 1 =                                                                                                        │
│     Property │ App.creates.work_item_comment.operation.inputFields[0].                                       │
│     Message  │ additionalProperty "helptext" exists in instance when not allowed                             │
│     Links    │ https://github.com/zapier/zapier-platform-schema/blob/v8.4.2/docs/build/schema.md#fieldschema │
└──────────────┴───────────────────────────────────────────────────────────────────────────────────────────────┘
```

### Version Info

- Version info: zapier-platform-cli/8.4.2
zapier-platform-core/8.4.2
node/v10.13.0
- Operating System: Windows 10 
- App id: 21129

**Comment by xavdid** [comment]
This was fixed back in https://github.com/zapier/zapier-platform/pull/63 but are just shipping it now. Later today, you'll be able to update to `v9.0.0` of the CLI and it'll work as expected. 😁
