### ISSUE TITLE
Expose the Zap/App that triggered an Action

### ISSUE THREAD

**Issue by kk-hainq** [zapier/zapier-platform#115]
Hi guys and thank you for an awesome platform!

We're having an action that creates some messages in our databases and we'd like to know the origin of them. We're storing triggers' corresponding zap id via `performSubscribe` then find their steps via https://api.zapier.com/v1/zaps, but actions don't seem to support `performSubscribe` and don't include zap id in their `perform` request's metadata.

Can you show us a way to get the Zap/App that triggered an Action? If this feature is missing, can we request or help implement it? Thank you.

**Comment by xavdid** [comment]
Hi there!

For privacy reasons, we don't expose which apps are triggering your actions (or the actions to your triggers). Sorry about that!
