### ISSUE TITLE
CLI completion scripts only available on GitHub and do not appear to be current

### ISSUE THREAD

**Issue by braderhart** [zapier/zapier-platform#118]
### Current Behavior
Completion scripts for CLI are only available on GitHub and are not the same if generated locally. This makes it difficult to package them for Linux distros that utilize NPM to build the package:

https://aur.archlinux.org/packages/zapier-platform-cli/

### Desired Behavior
Include updated completion scripts in the NPM package, or create a CLI option to generate them.

**Comment by xavdid** [comment]
@braderhart thanks for flagging! We're in the middle of a refactor right now and I think you're right that our scripts are out of date. We're wrapping that work soon and I'll make sure those scripts are appropriately updated. 

Thanks!

**Comment by xavdid** [comment]
This is slated for release in CLI 9.1.0, coming soonish.

Thanks for filing! 

https://zapier.github.io/zapier-platform/#command-line-tab-completion
