### ISSUE TITLE
For hooks, provide access to bundle.subscribeData in perform function

### ISSUE THREAD

**Issue by jstlaurent** [zapier/zapier-platform#12]
## What would you like to change?
The *bundle.subscribeData* object is available in the **performUnsubscribe** function defined on *hook* operations. It makes it easy to keep a reference on the hook to be deleted.

It might also be useful to have it accessible in the **perform** function. In my particular use case, my platform generates a unique token when the webhook is registered, that allows clients to validate the origin of requests. It would be stored in *bundle.subscribeData*. I would like to be able to do something like this in my **perform** function:

```
const getMyThing = (z, bundle) => {
    const {instance, token} = bundle.cleanedRequest;
    if (token !== bundle.subscribeData.token) {
        throw new Error(`Validation token '${token}' is not the expected value.`);
    }
    return [instance];
}
```

## Your Environment
* CLI Version (`zapier -v`): zapier-platform-cli/5.1.0, zapier-platform-core/5.1.0, node/v6.10.3
* Operating System and version: MacOS 10.13.4

**Comment by coonmoo** [comment]
@xavdid any updates on this? We'd like to access the subscription id in the performList request

**Comment by xavdid** [comment]
@coonmoo can you talk a little more about your use case for that? The `performList` is only used during zap setup, so at that point, there hasn't been a subscription id created yet (since the zap is not yet on).

**Comment by coonmoo** [comment]
Got it, thanks. I thought `performList `is also called for polling new data

**Comment by xavdid** [comment]
No worries! Hook zaps don't poll at all (except for setup).

**Comment by jeansimon** [comment]
This feature has been implemented on the server and is available to apps on all versions. Let us know if you have any questions!
