### ISSUE TITLE
Add command to change multiple env variables at once

### ISSUE THREAD

**Issue by nicoaravena** [zapier/zapier-platform#13]
## Add command to change multiple env variables at once

As a developer I would like to have a cli command that let me change env variables easily. This will help to move around different environments.

At the moment I need to do `zapier env <version>  <variable> <value>`  and I have multiple variables that depends on the develop, stage or production environment.

So a command like `zapier bulk <version> <file_name>` should be awesome, changing my environment in one easy step, improving the develop process.

As a fact, my team has two zapier apps, one for production and other for development, all with isolated variables for security purpose.

**Comment by xavdid** [comment]
this is available in CLI 9.0.0. 

https://zapier.github.io/zapier-platform/cli#envset

Thanks for filing!
