### ISSUE TITLE
Node 12 support

### ISSUE THREAD

**Issue by newtack** [zapier/zapier-platform#135]
### Current Behavior
AWS Lambda version is pinned to Node 8
### Desired Behavior
AWS supports latest stable Node version (version 12). This comes with latest Javascript features minimizing the need to transpile when using newer JavaScript features.

**Comment by xavdid** [comment]
@newtack Hey, thanks for flagging that!

We just got our Node 10 support up (in core version 9.0.0) and are planning on node 12 for the next major version. No current timeline, but it's definitely on our roadmap.

**Comment by eliangcs** [comment]
Core v10 now runs on Node 12. Closing.
