### ISSUE TITLE
Zapier Platform Docs broken in Firefox

### ISSUE THREAD

**Issue by ry167** [zapier/zapier-platform#136]
### Bug Description

The Platform docs located at https://zapier.github.io/zapier-platform/ are quite broken in Firefox: 
![image](https://user-images.githubusercontent.com/961043/71501437-6d945380-28cf-11ea-92d5-09d2daa3f0db.png)

Issue still occurs with all extensions and tracking protection turned off.

### Reproduction Steps

1. Open Firefox (latest version or close to it)
2. Navigate to https://zapier.github.io/zapier-platform/
3. Scroll the page until you find overlapping content that is unreadable.

### Misc

I had a small go at fixing the CSS myself but it seems like a pretty deep issue that casual inspect element hacking won't resolve. Best of luck

**Comment by xavdid** [comment]
Previously, this was fixable by resizing the FF window (any amount will do).

That said, I tried it just now and couldn't reproduce on the latest version of FF (72.0). Are you still seeing the issue after updating?

**Comment by ry167** [comment]
Woah I'm surprised that a Firefox updated fixed that. Nice call @xavdid - Thanks!
