### ISSUE TITLE
CHANGELOG.md incorrect format error is misleading

### ISSUE THREAD

**Issue by joshuathompson** [zapier/zapier-platform#15]
If you don't have a trailing newline at the end of your `CHANGELOG.md` file then the CLI will fail with: 

```Warning! Changelog not found. Please create a `CHANGELOG.md` file in a format similar to https://gist.github.com/xavdid/b9ede3565f1188ce339292acc29612b2, with user-facing descriptions``` 

I'm okay with it wanting it in the exact format but the error message made it seem like the file was in the wrong directory / didn't exist.

UPDATE:
This also is the case if you don't have an empty line between the version number and the bullet points.

## What would you like to change?
Improve error messaging about validating the file structure or more forgiving validation.

## Your Environment
* zapier-platform-cli/7.0.0
* zapier-platform-core/7.0.0
* node/v8.10.0
* OSX High Sierra 10.13.3

**Comment by eliangcs** [comment]
Confirmed this is still valid as of v13.0.0. Added to our internal Jira backlog: [PDE-3820](https://zapierorg.atlassian.net/browse/PDE-3820).

**Comment by kola-er** [comment]
This was resolved in [PR](https://github.com/zapier/zapier-platform/pull/653) and shipped in v15.0.0. Closing this as done.
