### ISSUE TITLE
How to Handle files in Zapier Platform UI

### ISSUE THREAD

**Issue by nitsuj99** [zapier/zapier-platform#158]
How do I handle a file a file response in my App when building in Zapier UI?

I've made a simple action that downloads a file from a URL, but there is no documentation around Files for Platform UI and how to return the response in the correct format for Zapier to recognise as a file. 

It only is referred to in CLI documentation using Hydrate which doesn't appear to work in UI.

I want my app to download a file and pass it to the next app in Zapier.

https://platform.zapier.com/docs/actions

**Comment by xavdid** [comment]
Hi there! Files and hydration are considered "advanced" actions and are only currently available in the CLI. There are docs about this here: https://platform.zapier.com/docs/vs

I'd recommend exporting your UI app to the CLI so you can continue development on it there. There's instructions for that here: https://platform.zapier.com/docs/export
