### ISSUE TITLE
Built-in session auth refresh handler interfering with developer intention

### ISSUE THREAD

**Issue by om4csaba** [zapier/zapier-platform#164]
### Bug Description

According to the docs and session auth example, you should throw a z.errors.RefreshAuthError, inside an after-response middleware [function](https://github.com/zapier/zapier-platform/blob/master/examples/auth/session.js#L53..L55).

But in reality, the platform was automatically adding a refresh [method](https://github.com/zapier/zapier-platform/blob/master/packages/core/src/http-middlewares/after/throw-for-stale-auth.js), handler.

(Registered here: https://github.com/zapier/zapier-platform/blob/master/packages/core/src/tools/create-app-request-client.js#L56-L64.)

This behaviour stops the App developer to handling 401 responses, like, wrong username/password. 

I think, either a config option to opt-out the inclouding the handler, like OAuth2, or prioritising the developer-defined session refresh method would solve this issue.

### Reproduction Steps

Try to catch the thrown error.

```js
    appTester(App.authentication.test, bundle)
      .then(response => {
        response.status.should.eql(401);
        done();
      })
      .catch(error => {
        // This is not working. For 401 response, the platform throwing an error.
        error.message.should.containEql('Session key needs refreshing.');
        done();
      });
``` 

### Version Info

- Version info: zapier-platform-cli/9.1.0 darwin-x64 node-v10.19.0
- Operating System: Mac OS X 10.15.3

**Comment by rnegron** [comment]
Hello, thank you for taking the time to submit such a descriptive issue. That said, given that it has been some time since this issue was created and it may be stale, I am going to go ahead and close it. Please feel free to open a new issue if necessary!
