### ISSUE TITLE
Response Header access in CLI Documentation is not correct   

### ISSUE THREAD

**Issue by om4csaba** [zapier/zapier-platform#178]
### Bug Description

The CLI Documentation (https://github.com/zapier/zapier-platform/blob/master/packages/cli/README.md) have multiple incorrect info about requests/response header access.

####  HTTP Response Object

Neider of the mentioned methods are working: https://github.com/zapier/zapier-platform/blame/master/packages/cli/README.md#L2090-L2091

Sample location: https://github.com/zapier/zapier-platform/blame/master/packages/cli/README.md#L2101-L2102

Instead of the above methods, the `response.headers.get('Content-Type')` is working (in a case insensitive manner).

(Spotted in a test: https://github.com/zapier/zapier-platform/blob/master/packages/core/test/logger.js#L25)

### Version Info

- Version info: zapier-platform-cli/9.1.0 darwin-x64 node-v10.19.0
- Operating System: Mac OS X 10.15.3
- App id: 70879

(EDIT: removed the reference about the `bundle.cleanedRequest`: not an actual bug)

**Comment by codebycaleb** [comment]
Hey @om4csaba - I'm digging in on issues a bit this week and I saw this one. I believe a fix was pushed to support bracket access with https://github.com/zapier/zapier-platform/pull/253 and released with version `10.0.0`. Could you give that another try and close this out if it's working as expected?

**Comment by om4csaba** [comment]
Hi @codebycaleb 

Yes, It's working now. All three method can access the same header:

```
response.headers.get('X-WordPress-GMT-Offset')
response.headers['X-WordPress-GMT-Offset'];
response.getHeader('X-WordPress-GMT-Offset')
```

I only tested in a case-sensitive manner. 

platform/cli version is the asem: `10.1.1 darwin-x64 node-v12.18.4`

Let me know if you need more test.

**Comment by codebycaleb** [comment]
Thanks for giving it a test! Since it's working now in case-sensitive and case-insensitive, I'm going to close this out. 😁
