### ISSUE TITLE
Authentication via child window

### ISSUE THREAD

**Issue by Majed6** [zapier/zapier-platform#180]
Hi,

I have a custom authentication with user key and api key. For better user experience, I would like to implement something similar to [this](http://www.gethugames.in/2012/04/authentication-and-authorization-for-google-apis-in-javascript-popup-window-tutorial.html )

Where a user clicks a button in my Zapier integration. That button opens a popup window/tab for login in my website. As soon as the user logs in, I'll capture both keys and store them in the input fields.

Is that possible?  

Thanks

**Comment by xavdid** [comment]
Great question! My gut is that won't work, but it's not something we've designed for or against. You're welcome to give it a shot!

In any case, we probably wouldn't add that right now since it's sort of an uncommon use case. A regular oauth flow is more common (if that's possible)
