### ISSUE TITLE
"Load more" in Lambda step not working 

### ISSUE THREAD

**Issue by PierreBergamin** [zapier/zapier-platform#191]
### Bug Description

We are trying adding a AWS Lamda invocation as a step to a Zap. Unfortunately, only a subset of our functions are listed in the dropdown. I can see a XHR request for the second "page" (page 1) but it doesn't render in the list. No requests for 3rd page get triggered (it's where I'm expecting to see my function). 

### Reproduction Steps

*NOTE*: In order to reproduce this bug, you need a large amount of lambda functions in your AWS account (113 here).

1. Add a step to invoke Lambda
2. Add AWS secret and Key
3. Select region
4. Click on dropdown to select function.
5. Scroll down, the first page (50 items) are rendered
6. Click _"Load More"_. I can see the XHR request being successful in the Network Tab but the rendered list doesn't update.

**Comment by xavdid** [comment]
@PierreBergamin Is this an issue you're having with a Zapier integration you're developing, or with the existing [Zapier Lambda Integration](https://zapier.com/apps/aws-lambda/integrations)?

**Comment by PierreBergamin** [comment]
@xavdid it's with the Zapier Lambda Integration

**Comment by xavdid** [comment]
Got it! In that case, https://zapier.com/contact-us is the best place to get help. This repo is for issues concerning Zapier developers. ​Let me know if you've got any other questions!
