### ISSUE TITLE
Content between double curlies is not visibile on the Docs website

### ISSUE THREAD

**Issue by Case-E** [zapier/zapier-platform#199]
The content between double curlies on the line below doesn't show up on the docs page.

https://github.com/zapier/zapier-platform/blob/40c5dd0cbc2af0b99a6568e7c0a8d24cb8847230/docs/index.html#L3266

If we are using Jekyll, then it is probably because of that we aren't seeing the double curlies or because of our own app. 

The section below this line shows the content properly as it is enclosed in the `code` tags.

https://github.com/zapier/zapier-platform/blob/40c5dd0cbc2af0b99a6568e7c0a8d24cb8847230/docs/index.html#L3292

![image](https://cdn.zappy.app/c8e65bfbd9f6e41e6d57372c1ad3bbe0.png)

We may need to identify other areas in the docs like this. This can make it very confusing for the users.

**Comment by codebycaleb** [comment]
Hey @Case-E! This was indeed a Jekyll issue. I resolved it last week though with https://github.com/zapier/visual-builder/pull/132
