### ISSUE TITLE
z.request() should be able to take custom beforeRequest and afterResponse functions

### ISSUE THREAD

**Issue by johnnyleitrim** [zapier/zapier-platform#20]
My particular use case is that I have a generic error handler configured in `App.afterResponse`.  However, for some requests, 404 or other errors are ignorable errors (but would be considered errors for other requests).

Ideally, it would be possible to specify a custom `afterResponse` list of methods, which would be executed instead of the `App.afterResponse`.  This would allow for custom error handling for those requests, while leaving the generic error handling in place for all other requests.

## What would you like to change?
```javascript
const App = {
  beforeRequest: [addAuthorizationHeader],
  afterResponse: [checkSuccessResponse],
}
```

It would be nice if I could override the middleware handlers for specific requests:
```javascript
return z.request('http://my.website.com/api'
  {
    method: 'POST',
    afterResponse: [customCheckSuccessResponse],
  });
```
In this case, only `customCheckSuccessResponse` would be executed after the requests.

**Comment by eliangcs** [comment]
I'm closing as "won't do". We see this would be convenient but there are ways to get around. For instance, in the global middleware `App.afterResponse` you could skip the middleware with an `if` if it doesn't apply to the inflight request. Or, you could write a global `afterResponse` that executes `response.afterResponse` if it's present in the response object.
