### ISSUE TITLE
Allow scope to be a function that returns a string in AuthenticationOAuth2ConfigSchema

### ISSUE THREAD

**Issue by awilson9** [zapier/zapier-platform#207]
### Current Behavior
Can only set scope to a string

### Desired Behavior
Would be nice if we could define a function that returns a string. My use case is allowing the user to pick the requested scope prior to sending the auth request to our application. Defining the dropdown with available menu items works fine, but I can't see a way to reference or map them to a scope string.

**Comment by xavdid** [comment]
That would be cool, we'll look into it!

**Comment by zapzap** [comment]
This issue has been copied into our private issue tracker  (as [PDE-1505](https://zapierorg.atlassian.net/browse/PDE-1505)). Thanks for the report! We'll update this as we learn more.
