### ISSUE TITLE
Zapier integration logs are not being collected

### ISSUE THREAD

**Issue by awilson9** [zapier/zapier-platform#208]
### Bug Description

My Zapier integration is definitely making requests using z.request, and is filled with several z.console.log statements as well. I'm receiving an error in oauth2 that I'm trying to debug with logs, however `zapier logs` is empty. 

### Reproduction Steps
command:

```
zapier logs
```

Actual Response:

```
✔ Loading logs
No logs found. Try adding some `z.request()`, `z.console.log()` and doing a `zapier push`!
```

Expected Response:
Logs that should be logged by the code posted below

Here's the code that's being ran
```
const getAccessToken = async (z: ZObject, bundle: Bundle) => {
  z.console.log(bundle.inputData);
  const response = await z.request(`${getAuthBaseUrl()}/${authUrlPath}/token`, {
    method: 'POST',
    body: {
      code: bundle.inputData.code,
      client_id: process.env.CLIENT_ID,
      client_secret: process.env.CLIENT_SECRET,
      grant_type: 'authorization_code',
      redirec_uri: bundle.inputData.redirect_uri
    },
    headers: {
      'content-type': 'application/x-www-form-urlencoded'
    }
  });
  z.console.log(response);
  if (response.status !== 200) {
    throw new z.errors.Error(
      'Unable to fetch access token: ' + response.content,
      'GetAccessTokenError',
      response.status
    );
  }
  z.console.log(response.json);
  return {
    ...response.json,
    org_id: bundle.inputData.orgID
  };
};
```

This request is failing as the zapier auth modal is displaying an error message that is only returned by making this particular call.

### Version Info

- Version info:  zapier-platform-cli/9.4.0 linux-x64 node-v12.16.1
- Operating System: Ubuntu 18.04.4 LTS (Bionic Beaver)
- App id: 101396

**Comment by awilson9** [comment]
Update: I'm able to view logs from the browser now, but am still getting an empty response from the CLI

**Comment by om4csaba** [comment]
The same problem here started around a week ago with zapier-platform-cli 10.0.1

**Comment by codebycaleb** [comment]
@awilson9 - can you reproduce this? I've not been able to detect a difference between the browser and the command line in my testing. Note that `zapier logs` defaults to logs for your CLI logged in user, so if the account you're testing with is different, you'll want to add a `--user=user@example.com` flag.

**Comment by codebycaleb** [comment]
I worked with @om4csaba outside of GitHub to diagnose what was going wrong for their team. I'm closing this out now though as we haven't seen other reports. @awilson9 if you run into further issues in the future, feel free to reopen!
