### ISSUE TITLE
zapier push --without-style does not work

### ISSUE THREAD

**Issue by sultanbadza** [zapier/zapier-platform#25]
The CLI command "zapier push --without-style", as described at https://zapier.github.io/zapier-platform-schema/build/schema.html#basichookoperationschema does not work. It works well with zapier validate, but it still cannot push any data without style even for a private app. 

There response I get is:
zapier push --without-style

Errors running command `zapier push --without-style`:

!!!   Unexpected keyword argument --without-style

For more information, run `zapier help push`.

**Comment by sultanbadza** [comment]
I tried "zapier push" alone and I get an error. When I tried it with "--without-style" it gave me this error above. When I try "zapier validate --without-style" it works well, but it is pretty useless that way. :)

**Comment by xavdid** [comment]
Right, I was wondering about the error you get when you just run `zaiper push` without the flag. why does that fail exactly?

**Comment by sultanbadza** [comment]
It fails because there is a performList missing for a webhook call polling.
We are using private app so we do not want to poll as we do not have GET
endpoints available for all of our events. We want to skip performList and
to get live data triggered manually from the app when testing a trigger.

sri, 26. jun 2019. 03:12 pošiljalac David Brownman <notifications@github.com>
je napisao:

**Comment by xavdid** [comment]
We've changed how we do validations so this should be fixed on the latest version (`v9.0.0`, releasing later today).

I'll also remove references to that flag that doesn't exist. thanks a bunch!
