### ISSUE TITLE
CLI: env vars - docs outdated?

### ISSUE THREAD

**Issue by thomasklein-winemaker** [zapier/zapier-platform#259]
### Bug Description

The CLI only supports the `zapier env:<get|set>` syntax as documented on https://zapier.github.io/zapier-platform/cli#envget.
However, https://platform.zapier.com/cli_docs/docs#environment and https://zapier.github.io/zapier-platform/#Environment list another usage e.g. `zapier env 1.0.0 MY_SECRET_VALUE 1234`.

### Version Info

- Version info: zapier-platform-cli/10.0.1 darwin-x64 node-v12.18.3
- Operating System: OSX

**Comment by xavdid** [comment]
Ah yes, they are. 

The source of truth for the mechanics of each CLI method is https://zapier.github.io/zapier-platform/cli and the CLI helpdocs themselves (they're synced up with the code). Other docs sometimes fall behind. 🙈 

We'll get that fixed up!
