### ISSUE TITLE
A user on a legacy plan see's the previous Pro plan on the upgrade page

### ISSUE THREAD

**Issue by lauragiles-zapier** [zapier/zapier-platform#263]
### Bug Description

When the user goes to upgrade their plan to the latest pro plan with unlimited Zaps the change plan button on the billing page takes them to this link here - https://zapier.com/app/billing/plans?context=315734 and shows the pro plan as the legacy with the 25 zap limit

Zappy screenshot here: https://zappy.zapier.com/f0e7ec3e008eefd7995b02debd68d4fb.png

If you load https://zapier.com/app/billing/plans when logged in to the account it shows the correct plan.

Customer account registered under - _email_ but they are looking to upgrade so may not be shown

Video showing the trouble here - https://drive.google.com/file/d/1DZNfDW_A3MluzmWz99zbW4N6ZC_gu1-z/view?usp=sharing

**Comment by xavdid** [comment]
@lauragiles-zapier closing, because I think you meant to file this as an internal bug. As far as I can tell, none of the mentioned pages are platform related
