### ISSUE TITLE
Can't run zapier build

### ISSUE THREAD

**Issue by iosepa** [zapier/zapier-platform#267]
### Bug Description

Can't run zapier build with the CLI. I get npm ERR! missing script: _zapier-build

### Reproduction Steps

npm install -g zapier-platform-cli
zapier init myApp --template minimal
cd myApp
npm install
zapier build
result: "
✖ Running _zapier-build script
 ›   Error: npm ERR! missing script: _zapier-build
 ›
 ›   npm ERR! A complete log of this run can be found in:
 ›   npm ERR!     /Users/iosepa/.npm/_logs/2020-09-01T20_17_14_249Z-debug.log
 ›
 ›
 ›   re-run this command with `--debug` for more info
"

--debug gives same error of missing script

I've uninstalled and reinstalled zapier-platform-cli with no change

1.

### Version Info

- Version info: zapier-platform-cli/10.1.0 darwin-x64 node-v12.18.3
- Operating System: MacOS 10.12.6
- App id: App independent

**Comment by xavdid** [comment]
Thanks for reporting! We actually just merged a fix for this and will release it in the next day or so (https://github.com/zapier/zapier-platform/pull/265). 

Until then, you can either:

* downgrade your CLI to `10.0.1`
* define a `_zapier_build` script that either does nothing (`""`) or does a simple `echo bugfix`

Sorry for the hassle here!

**Comment by xavdid** [comment]
a fix has been released as Zapier CLI 10.1.1, available now!
