### ISSUE TITLE
Confusing examples and anti-examples

### ISSUE THREAD

**Issue by colesimmons** [zapier/zapier-platform#284]
Consider the examples and anti-examples for [ResourceMethodCreateSchema](https://github.com/zapier/zapier-platform/blob/master/packages/schema/docs/build/schema.md#resourcemethodcreateschema).

<img width="1075" alt="Screen Shot 2020-10-20 at 2 49 57 PM" src="https://user-images.githubusercontent.com/4589953/96648274-f60f3500-12e3-11eb-8621-44c9f746d3da.png">

The only difference between the 2nd example and the anti-example is the presence of `hidden` in `display`, which is a valid key for BasicDisplaySchema.

**Comment by codebycaleb** [comment]
Hey @colesimmons! I think I can clarify this one. The focus here is that an `operation.sample` is required _unless_ `display.hidden` is `true`. That nuance is covered in the description of [BasicActionOperationSchema](https://github.com/zapier/zapier-platform/blob/master/packages/schema/docs/build/schema.md#basicactionoperationschema).

> What does a sample of data look like? Will use resource sample if missing. Requirement waived if `display.hidden` is true or if this belongs to a resource that has a top-level sample

**Comment by colesimmons** [comment]
@codebycaleb Ah, thanks Caleb! That makes sense, though I still wouldn't consider that an anti-example as it could belong to a resource that has a top-level sample.

I'll go ahead and close this since it does answer my question. I'll try to put together a PR when I have a chance that will hopefully clarify some of the points where I got stuck while working on Abstract's integration.

**Comment by xavdid** [comment]
Appreciate that - the `examples` and `anti-exampes` are a little confusing in the first place because they're only there to show json that is either valid or invalid based on the schema. So they're not _examples_ in the traditional sense of showing the reader a basic way to do something.
