### ISSUE TITLE
New inputField default state not visible after migration

### ISSUE THREAD

**Issue by om4csaba** [zapier/zapier-platform#289]
### Bug Description

When a new version of the integration introduces a new `inputField` with a default value, that value not visible in migrated Zaps. But working fine for a newly created Zap. However, in both cases, the value properly set, even if a field `required` the interface lets the user continue.

The problem is valid for Triggers, Actions and Searches as well.

### Reproduction Steps

1. Add a new `inputField` to your application. For example:

```js
{
    key: 'setTrue',
    required: true,
    type: 'boolean',
    default: 'Yes',
    choices: ['Yes', 'No']
}
```

2. Push to zapier as a new version
3. Migrate a user who had a Zap configured and running with the app
4. Edit the Zap, but don't touch the new field, just press continue. Even with `required: true`, the interface let continue.
5. Run a task and see the new field in the task log or the CLI bundle log.

### Version Info

* CLI version: 10.1.2
* Node.js version: v12.19.0
* OS info: darwin-x64
* `zapier-platform-core` dependency: 10.1.1

**Comment by xavdid** [comment]
That's an interesting one! I'll run that buy the editor team and let you know what we find.

**Comment by stevemolitor** [comment]
@om4csaba Got a zap where we can reproduce the "invisible" default value in the editor? Thanks!

**Comment by xavdid** [comment]
@om4csaba also, can you double check it's reproducible with a "regular" string field with a default? It's a little odd to have a `boolean` field with `choices` and I want to make sure that's not confounding us here.

**Comment by om4csaba** [comment]
@stevemolitor This is the WooCommerce app (id 67372), the new version (2.1.0) introduced the new input. I sent an invite to your email. Looks for the `expandMeta` ('Add Meta Data Fields'), which is added to every trigger, search and action.

@xavdid the logic behind using `choices` with `boolean` was, that we wanted a more natural read in the interface:
 "Add Meta Data Fields: Yes/No" versus "Add Meta Data Fields: True/False"

I will test with string type and reporting back.

**Comment by om4csaba** [comment]
I created test Zaps:

- ID 104484427: to demonstrate the current behaviour
- ID 104484427: changed the  `expandMeta` to `string` 

In both cases, the result the same as initially reported. But I did not test removing the `required` flag. 

Here again, the concrete `inputField` config with explanations of the decisions:

```js
{
    key: 'expandMeta',
    label: 'Add Meta Data Fields',
    type: 'boolean', // This is a feature flag
    required: true, // We always need it
    choices: ['Yes', 'No'], // To make the interface more user friendly
    default: 'Yes', // Enabled by default, opt-out for mitigate potential BC break
    helpText: '[...]',
    altersDynamicFields: true/false // True for create actions only, where controls displaying additional fields too
  }
```

After playing around with it, stumbled another issue:

The `required` flag was also not working as expected for this field. The user can clear the value, and still, the interface let continue, perhaps because the field has a default value.

**Comment by rnegron** [comment]
Given that it has been some time since this issue was created and it may be stale, I am going to go ahead and close it. Please feel free to open a new issue if necessary!
