### ISSUE TITLE
When you pass on a file (URL) using form-data it doesn't use the Content-Disposition filename

### ISSUE THREAD

**Issue by mkasson** [zapier/zapier-platform#29]
This issue submission follows a conversation with Fokke.

Your "creates/upload.js" shows use of **Form-Data** and **request** to upload a file presented to a create by a trigger.  However, I have seen **Form-Data** is not receiving the filename from the Content-Disposition line.  I have had to set filename manually (providing a placeholder) using the [Alternate Submission Methods](https://www.npmjs.com/package/form-data#alternative-submission-methods) and submitted PR #7 relating to this.  

**Form-Data** says that it "can recognize and fetch all the required information from common types of streams (fs.readStream, http.response and mikeal's request)".  This suggests that the filename is not getting to **request** and/or **Form-Data** correctly. (Perhaps the issue is in stashing and/or dehydration - though I admit I am not super familiar with the impact of those.)  Fokke and I have both observed Form-Data using the value from **path** in [this method](https://github.com/form-data/form-data/blob/028c21e0f93c5fefa46a7bbf1ba753e4f627ab7a/lib/form_data.js#L217)

Thank you for your attention to this.

**Comment by rnegron** [comment]
Given that it has been some time since this issue was created and it may be stale, I am going to go ahead and close it. Please feel free to open a new issue if necessary!
