### ISSUE TITLE
Injected environment variables can't be used in any imports

### ISSUE THREAD

**Issue by FokkeZB** [zapier/zapier-platform#30]
This won't work in a Babel app:

```js
import zapier from 'zapier-platform-core';
zapier.tools.env.inject()
import { authData } from './testUtils';
```

Where `testUtils.js` is:

```js
export const authData = {
  api_key: process.env.API_KEY,
};
```

This is because Babel will hoist import so `./testUtils` will be imported **before** `zapier.tools.env.inject()` runs.

I've tried to find workarounds, but the only viable seem to be either changing `authData` to be a function _or_ don't use environment variables in imported scripts.

I wonder `zapier-platform-core` should automatically inject environment variables on its import if `process.env.LOADED_MOCHA_OPTS === 'true'` (which seems to be the only environment variable set if you run tests).

Any ideas?

**Comment by rnegron** [comment]
Given that it has been some time since this issue was created and it may be stale, I am going to go ahead and close it. Please feel free to open a new issue if necessary!
