### ISSUE TITLE
Unable to create dependent input field from dynamic field.

### ISSUE THREAD

**Issue by manishjaingit** [zapier/zapier-platform#32]
I wanted to create a form where below 4 fields of the form is dependent on the option that user choose in the middle of the form.

I have read the Zapier document and also used their script but unable to succeed. i think something i am missing to implement.

pls guide

**Comment by xavdid** [comment]
can you please update your question to include what you've tried already and what about it isn't working?

**Comment by manishjaingit** [comment]
Here I asked also https://stackoverflow.com/questions/56804655/how-to-make-dynamic-fields-in-zapier-platform can you please guide me where I am doing wrong.

**Comment by xavdid** [comment]
i've answered on stackoverflow. In the future, please only ask in a single place, not multiple.
