### ISSUE TITLE
'Files can only be stashed within a create' error thrown for resource based creates

### ISSUE THREAD

**Issue by owarij** [zapier/zapier-platform#334]
### Bug Description

If you use z.stashFile in your CLI integration and it's a resource-based/generated create app - You'll get an error thrown -

 “Files can only be stashed within a create or hydration function/method”

![image](https://user-images.githubusercontent.com/24947557/108499513-c9b0f880-7284-11eb-8254-0711d4e3cb44.png)

It looks like the check here may need some updating/love - https://github.com/zapier/zapier-platform/blob/fb60ef9ba9/packages/core/src/tools/create-file-stasher.js#L94

**Comment by zapzap** [comment]
This issue has been copied into our private issue tracker  (as [PDE-2030](https://zapierorg.atlassian.net/browse/PDE-2030)). Thanks for the report! We'll update this as we learn more.

**Comment by xavdid** [comment]
Hey @owarij I think you're right that check needs updating. I'm having a little trouble reproducing the bug in a test project. do you mind sharing/pointing me towards your resource & test? Thanks!
