### ISSUE TITLE
HTTP 204 responses raise error

### ISSUE THREAD

**Issue by jmschneider** [zapier/zapier-platform#355]
### Bug Description

When using [`executeHttpRequest`](https://github.com/zapier/zapier-platform/blob/zapier-platform-schema%4010.2.0/packages/core/src/execute.js#L13-L23) with an API that returns `204 No Content`, it raises a "Response needs to be JSON, form-urlencoded or parsed in middleware." error. Since the API is saying there is no content, it should be acceptable to return a `null` or `{}` instead. For our API's `performUnsubscribe`, we do not return any content upon success.

### Reproduction Steps

```JS
z.request({ url: 'https://httpstat.us/204' })
```

### Version Info

- Version info: 10.2.0
- Operating System: OS X
- App id: 112384

**Comment by zapzap** [comment]
This issue has been copied into our private issue tracker  (as [PDE-2278](https://zapierorg.atlassian.net/browse/PDE-2278)). Thanks for the report! We'll update this as we learn more.

**Comment by xavdid** [comment]
@jmschneider I dug into this and I think it's actually working as expected. Ultimately, triggers need to return arrays and creates need to return objects. Hopefully we can parse something out of an http response, but if not, you need to handle it manually.

In this case, there's no response at all. Given that, you should add middleware to return an empty object:

```js
module.exports = {
  //
  afterResponse: [
    (response) => {
      if (response.data === undefined) {
        response.data = {};
      }
      return response;
    },
  ],
}
```

That should ensure any failing tests pass!
