### ISSUE TITLE
[feature] add aliases to the DynamicFields

### ISSUE THREAD

**Issue by kaznovac** [zapier/zapier-platform#360]
### Current Behavior
changing the `Field`'s `key` property creates a breaking change for all zap users

### Desired Behavior
add ability to specify alias on the field (an array of strings on the `Field` schema, that can be used instead of the `Field`'s`key`)

this can be extended further (and more dynamically) by allowing functional value getters on the field

**Comment by xavdid** [comment]
This is a cool idea! Based on the way our backend is structured, I'm not sure it's possible at this time. But we'll leave it open if others have interest too!
