### ISSUE TITLE
a way to programmatically skip the resource's get operation?

### ISSUE THREAD

**Issue by kaznovac** [zapier/zapier-platform#381]
i have a `resource` with `search` operation that returns the enough information in results, but in the logs i see the zapier platform follows the `search` with immediate `get` operation (i.e. `searches.teamSearch.operation.performGet`)

is there an opt-out option from the code per operation (i'd like to keep the `get` behavior after the `create` operation)?

**Comment by xavdid** [comment]
I don't think there's a way to skip the whole thing. But, if you can distinguish between an object that you need to do a `get` for and not, you can code it up:

```js
const performGet(z, bundle) => {
  if (bundle.inputData.someProp) {
    // already fetched data, no need to do it again
    return bundle.inputData
  }
  // make request, etc
}
```

This is an interesting FR though! i'll mark it as such and we'll think about it.

**Comment by kaznovac** [comment]
@xavdid thanks, this trick will do :)

**Comment by xavdid** [comment]
Cool! We'll close for now, but we're open to changing this behavior in the future.
