### ISSUE TITLE
performResume step not being run / callback not being waited for

### ISSUE THREAD

**Issue by cjroebuck** [zapier/zapier-platform#398]
### Bug Description

I'm using `z.generateCallbackUrl()` in `perform` step. I pass that url into my API and my API POST's back to the url after a few seconds. The `performResume` step is never run according to for e.g. `zapier logs`. Also, any Zap's I build using this integration do not seem to wait for the callback/performResume step, therefore I'm not able to get the actual final result from my webhook POST to pass to further steps in zap's.

### Code

```js
const createScreenshot = (z, bundle) => {
  const callbackUrl = z.generateCallbackUrl();
  const promise = z.request({
    url: 'https://api.myapi.com/v1/render',
    method: 'POST',
    params: {},
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/json',
    },
    body: {
      ...bundle.inputData,
      webhook_url: callbackUrl
    },
    removeMissingValuesFrom: {},
  });
  z.console.log("Returning from perform / createScreenshot");
  return promise.then((response) => ({ ...response.data, waiting_for: "performResume", callback_url: callbackUrl }));
}

const onScreenshotFinished = (z, bundle) => {
  z.console.log("In performResume / onScreenshotFinished", bundle.cleanedRequest);
  const responseBody = bundle.cleanedRequest;
  let screenshotUrl;

  if (responseBody.event === "render.succeeded") {
    z.console.log("render was processed successfully", responseBody);
    screenshotUrl = responseBody.result.renderUrl;
    return { screenshotUrl, ...responseBody };
  }

  z.console.log("render was not processed", responseBody);
  throw z.errors.Error("Screenshot was not successful");
}

module.exports = {
  operation: {
    perform: createScreenshot,
    performResume: onScreenshotFinished,
    ...
```

`zapier logs` output:

```

== Log
Returning from perform / createScreenshot
== Version
0.0.1
== Step
734453ad-8e7e-4229-a92c-e8ea4a8c908d
== Timestamp
2021-07-14T06:59:59-05:00

  Most recent logs near the bottom.
```

### Version Info

- Version info: 
```zapier -v
* CLI version: 11.0.1
* Node.js version: v14.3.0
* OS info: darwin-x64
* `zapier-platform-core` dependency: 11.0.1
```
- Operating System: macos
- App id: 139943

**Comment by cjroebuck** [comment]
## Steps to recreate

1. `mkdir -p zapier-callback-test`
2. `cd zapier-callback-test`
3. `zapier init --template callback . `
4.  `zapier register`
5. `zapier push`
6. Create a zap that uses zapier-callback-test action, for example, schedule -> zapier-callback-test -> google-drive. 
7. Notice that if you try to use the 'Predicted Result' output in a later action, it shows 'no data' - this should have been filled in by the callback / performResume step.



![image](https://user-images.githubusercontent.com/12208/125638749-09a785c7-818c-41d5-aea3-0f31e2ba432d.png)

**Comment by codebycaleb** [comment]
Hey @cjroebuck! Thanks so much for the report here. Reading your steps to reproduce has me wondering - have you tested this with a "live" Zap? It sounds like you might have been running it with the Test Step functionality in the editor. 

I don't think our docs currently cover the fine print there. This functionality is only supported for live Zaps right now (i.e. not during Zap setup). In order to make sure fields can be mapped in future Zap steps, you'll have to make sure your static `sample` for the trigger or action contains all of the fields you expect to receive after a callback. 

Sorry for the lack of clarity here! It's a fairly new feature, so we're still ironing out the fine details. If I'm off base and you have tested with a live Zap, could you drop the link to the Zap here and I'll take a finer look at the logs?

Thanks!

**Comment by cjroebuck** [comment]
Hi @codebycaleb, you’re right it was when I was creating a zap during the test setup that the field from the callback were not being filled in, I had to press ‘skip test’ in order to be able to finish creating a zap because the result field kept saying ‘no data’. 

I imagine this would cause some confusion when end users try to create zaps with my integration. I think even with a static sample, the output field from callback is still showing ‘no data’ when I try to configure a further action. I’ll need to go back and double check this though.

But yes when it is run with a live zap it is working as expected and I can see the correct fields from the callback. Sorry for opening the issue but I assumed that the test step would wait for the callback before continuing, or somehow acknowledge that it is waiting for a callback or something and the end user could either wait or if the callback really is going to take a long time, then skip waiting with some fake sample data used to configure the next steps

**Comment by codebycaleb** [comment]
> But yes when it is run with a live zap it is working as expected and I can see the correct fields from the callback. Sorry for opening the issue but I assumed that the test step would wait for the callback before continuing, or somehow acknowledge that it is waiting for a callback or something and the end user could either wait or if the callback really is going to take a long time, then skip waiting with some fake sample data used to configure the next steps

Totally fair point! I submitted that feedback for the Zap Editor team! 

For today, one potential route to make sure data is available during Zap setup would be to check `bundle.meta.isLoadingSample` (https://github.com/zapier/zapier-platform/tree/master/packages/cli#bundlemeta). Something like

```
  // set default `perform` results during Zap setup
  const defaults = { expectedField: "(this is a placeholder value)" };
  
  // later...
  
  return promise.then((response) => {
    const result = { ...response.data, waiting_for: "performResume", callback_url: callbackUrl };
    if (bundle.meta.isLoadingSample) {
      return { ...defaults, ...result };
    }
    return result;
  });
```

You could also theoretically skip the `isLoadingSample` check. I don't believe any values from `perform` get passed in a live Zap until `performResume` has run (which should override any previously returned values). 😄
