### ISSUE TITLE
Allow cloning app from Zapier to local machine

### ISSUE THREAD

**Issue by taragano** [zapier/zapier-platform#413]
### Current Behavior
Currently, I can push a local code to Zapier
### Desired Behavior
I'd like to also be able to have something similar to `git clone`, where I'm able to download an existing code, that's already in Zapier, and download it to my local machine.
Use cases:
1. Something happened to my local machine/files deleted etc., and I'd like to continue working on app with the code that already exists in Zapier.
2. Would like another developer to work on the app, and to let them `git clone` and/or `git pull` rather than me sharing the local folder.
This of course relates to both different apps (integrations) and different versions.

**Comment by xavdid** [comment]
@taragano You are _absolutely_ correct that you want a shared, cloud-based git repository. That said, Zapier itself is not the place for it. We recommend GitHub instead! 

It's free to make private personal repos and you may be able to share with others for free as well.  GitLab offers similar functionality. 

Given that there are two great options for your exact problem, this is not something we'll be pursuing. Thank you for bringing it up!
