### ISSUE TITLE
Make it possible to test run "the rest" of a zap

### ISSUE THREAD

**Issue by GibsDev** [zapier/zapier-platform#451]
### Current Behavior
You have to manually click through each step to test your whole zap.

### Desired Behavior
After selecting the test data from the trigger, I would like to be able to click one button to execute the rest of the steps in the zap with that trigger data.

**Comment by xavdid** [comment]
@GibsDev Thanks for filing this! 

This would fall to our editor team, which is separate from the dev platform team (that owns this repo). I've filed this in our internal UX feedback system and will go ahead and close this issue.
