### ISSUE TITLE
Support pnpm

### ISSUE THREAD

**Issue by nitwhiz** [zapier/zapier-platform#470]
### Current Behavior

The CLI supports npm and yarn out of the box.

### Desired Behavior

The CLI supports npm, yarn and pnpm out of the box.

**Comment by xavdid** [comment]
@nitwhiz Thanks for the request! We've got a lot of other stuff in the pipeline right now, but we'll keep this open for others to 👍 if they have the same request.

**Comment by nitwhiz** [comment]
@xavdid are pull requests welcomed, too?

**Comment by xavdid** [comment]
@nitwhiz they certainly are!
