### ISSUE TITLE
Choose field to use for duplication.

### ISSUE THREAD

**Issue by aarbar** [zapier/zapier-platform#552]
### Current Behavior

https://platform.zapier.com/docs/triggers
https://platform.zapier.com/docs/dedupe

Currently, Zapier uses the **Id** field to determine if a trigger should run (only run if the **Id** field has a new value).

### Desired Behavior

It would be good to choose this field? for example, it could be **_Id**.

### Reason

Our API returns **Id** for both Created/Updated flows. 
Created is fine because the **Id** is always new.
But Updated we have to generate a new ID for the trigger to run, and then save the original Id into SomeId.
This makes mapping Id's in actions more confusing for the end-user.

**Comment by rnegron** [comment]
👋🏻 Hello @aarbar, we don't currently have plans to alter this behavior of requiring an "id" field, but you can work around this restriction in your trigger code, [see the sample snippet here](https://github.com/zapier/zapier-platform/blob/main/packages/cli/README.md#why-are-my-triggers-complaining-if-i-dont-provide-an-explicit-id-field). This is also available via "code mode" for integrations built using the Visual Builder (see the "Custom or multiple ID fields" section [here](https://platform.zapier.com/docs/dedupe))
