### ISSUE TITLE
Command Injection on sub-dependency lodash.template via @oclif/plugin-help

### ISSUE THREAD

**Issue by mrjackdavis** [zapier/zapier-platform#555]
tldr; please update `@oclif/plugin-help` to `3.2.14` to fix a vulnerability in [`zapier-platform-cli`](https://github.com/zapier/zapier-platform/blob/master/packages/cli/package.json)

---

`lodash.template` package has a security vulnerability. See here https://security.snyk.io/vuln/SNYK-JS-LODASHTEMPLATE-1088054. The CVE rating is HIGH 7.2.

`@oclif/plugin-help` [version should be updated](https://www.npmjs.com/package/@oclif/plugin-help). I believe [3.2.14](https://www.npmjs.com/package/@oclif/plugin-help/v/3.2.14) would suffice.

Please consider `^` syntax so that your dependents can update patch versions without updates required to the repo

**Comment by rnegron** [comment]
Fixed in #739.
