### ISSUE TITLE
how to set clientId and secrect in cli app

### ISSUE THREAD

**Issue by comewithl** [zapier/zapier-platform#568]
how to set clientId and secrect in cli app，the cli app lock the oauthV2 config.

**Comment by kreddlear** [comment]
@comewithl My apologies for the late response! This repo is checked for bug reports, but not for questions. Please reach out to our developer support team via this form, they will be able to help you resolve this question. https://developer.zapier.com/contact

**Comment by comewithl** [comment]
这是来自洪俊贤的自动回复邮件。
