### ISSUE TITLE
`befores` and `afters` methods are in example but not schema docs.

### ISSUE THREAD

**Issue by woodhull** [zapier/zapier-platform#587]
### Bug Description

[befores and afters methods](https://github.com/zapier/zapier-platform/blob/master/example-apps/custom-auth/authentication.js#L65) are not part of the schema for cli authentication. I think these should be beforeRequest and afterResponse on the parent object?

**Comment by eliangcs** [comment]
Good question! `befores` and `afters` used in the example are "internal" in the `authentication.js` module. When we import `authentication.js` and export from `index.js`, it [becomes `beforeRequest` and `afterResponse`](https://github.com/zapier/zapier-platform/blob/e6e046588cfe8e6fcc75b6286608add0b8e321d8/example-apps/custom-auth/index.js#L15-L17).
