### ISSUE TITLE
[Feature Request]: Upgrade "node-fetch" library

### ISSUE THREAD

**Issue by kostelis** [zapier/zapier-platform#643]
### Current Behavior

We are having issues with implementing a multi-file response handling using the Zapier platform.

We have a server that returns multiple files as a response to Zapier's action call. It returns the response in a multipart/form-data way (we could make it a multipart/mixed or multipart/byteranges). However, the z.request() is not able to handle it.

### Desired Behavior / Feature Request

I noticed that 'node-fetch' (v3) library supports parsing the form data from the response. I can see that zapier-platform-core already uses 'node-fetch' lib, however it's older version v2.6.7.

Would it be possible to upgrade the [node-fetch](https://www.npmjs.com/package/node-fetch) to v3.2.10 or later?

**Comment by kostelis** [comment]
Hi there, I would like to note that the ```node-fetch``` library update is still very relevant and would be greatly appreciated. Thanks in advance!

**Comment by eliangcs** [comment]
Sorry for the delay here! We're still deciding if upgrading node-fetch to 3.x is necessary, considering Node.js 18 already has built-in [fetch API](https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch). So it's going to take a while.

As a workaround, I think you can get the response body and parse it using `new Response().formData()`. Example:

```js
// Set `raw` to true so you can use response.text()
const response = await z.request({ url, raw: true });  

// contentType is expected to be like "multipart/form-data; boundary=----xxx; charset=utf-8"
const contentType = response.headers.get('content-type');
const text = await response.text();

// Use the built-in Response object to parse the text, assuming you're using Node.js 18.x.
// https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#response
const form = await new Response(text, {
  headers: { 'content-type': contentType },
}).formData();

// The parsed result is a FormData object.
// https://developer.mozilla.org/zh-TW/docs/Web/API/FormData
// You can then iterate the form data using .entries(), for instance.
for (const [k, v] of form.entries()) {
  console.log(k, v);
}
```

@kostelis let me know if it works!

**Comment by kostelis** [comment]
Hi @eliangcs, thanks for the suggestion, it works!!
