### ISSUE TITLE
[Bug]: ResizeObserver - loop limit exceeded

### ISSUE THREAD

**Issue by bettysteger** [zapier/zapier-platform#645]
### Bug Description

When embedding zap templates with 

```
<script type="module" src="https://cdn.zapier.com/packages/partner-sdk/v0/zapier-elements/zapier-elements.esm.js"></script>
<link rel="stylesheet" href="https://cdn.zapier.com/packages/partner-sdk/v0/zapier-elements/zapier-elements.css"/>
<zapier-zap-templates ...></zapier-zap-templates>
```

an JavaScript error is thrown: `ResizeObserver loop limit exceeded`.  There are no error details. 

### Reproduction Steps

1. Embed zap templates 
2. Open page where you embedded the zap-templates

### Zapier Platform version

0

### Node.js version

0

### Your Operating System

macOS 13.3, Chrome v112

### npm/yarn version

yarn 1.22.19

**Comment by rnegron** [comment]
👋🏻 Hello @bettysteger! This looks to be a problem with the in-browser embedded experience. This repository is only for issues related to the Zapier Platform tools. For assistance on your issue, please do reach out to support via: https://developer.zapier.com/contact
