### ISSUE TITLE
Where is the latest changelog?

### ISSUE THREAD

**Issue by vaskevich** [zapier/zapier-platform#66]
Hi, I can't find the latest changelog for v8.3. Places I looked:
- https://github.com/zapier/zapier-platform-cli - archived, points to https://github.com/zapier/zapier-platform/tree/master/packages/cli
- https://github.com/zapier/zapier-platform/tree/master/packages/cli - no CHANGELOG.md, but the README has a broken link pointing to https://github.com/zapier/zapier-platform/blob/master/packages/zapier-platform-cli/CHANGELOG.md
- https://github.com/zapier/zapier-platform-core - archived, points to https://github.com/zapier/zapier-platform/tree/master/packages/core
- https://github.com/zapier/zapier-platform/tree/master/packages/core - has a CHANGELOG.md file that points to https://github.com/zapier/zapier-platform-cli/blob/master/CHANGELOG.md

Seems like there's a cycle with the latest changes nowhere to be found! 😅 Could you please update these links?

**Comment by codebycaleb** [comment]
Hey @vaskevich! It's definitely tripped me up before as well. The changelog is at the top level of this repo: https://github.com/zapier/zapier-platform/blob/master/CHANGELOG.md. Sorry for the confusion there! Feel free to push a PR to adjust any of those spots. 😁
