### ISSUE TITLE
[Bug]: throwing `new z.errors.RefreshAuthError()` doesn't retry `performUnsubscribe`

### ISSUE THREAD

**Issue by misterjoshua** [zapier/zapier-platform#664]
### Bug Description

In a hook-based trigger, when `new z.errors.RefreshAuthError()` is thrown during `performUnsubscribe` because an OAuth2 access token has expired, `refreshAccessToken` is called, but `performUnsubscribe` doesn't run again. As a result, my API never receives the unsubscribe message.

### Reproduction Steps

Here are traces from my OpenTelemetry instrumentation:

![image](https://github.com/zapier/zapier-platform/assets/644092/03b0f7b0-ab0b-439e-9359-bc930334b9fd)

In this trace, here's what I did:

- Created a zap with my app as a trigger
- Connected my account
- Got to the place where the Zapier web ui wants me to wait for the first event (`subscribe` @ 02:26:50)
- Waited until the access token expired then ran "test connection" from the Zapier web UI
- Observed as the first testAccess failed because it threw `z.errors.RefreshAuthError()` (02:31:41) 
- Observed as Zapier ran `refreshAccessToken` then re-ran `testAccess` - at this point, it's clear that `autoRefresh: true` works for connection testing
- Waited for the access token to expire then deleted the connection from the "app connections" screen in the Zapier web UI
- Observed that the unsubscribe failed because it threw `z.errors.RefreshAuthError()` (02:38:17)
- Observed Zapier attempting to run `refreshAccessToken` again
- But this is where it stops. It doesn't re-run the unsubscribe.

### Zapier Platform version

14.1.1

### Node.js version

18.13.0

### Your Operating System

Linux Ubuntu 22.04 in WSL

### npm/yarn version

3.5.1

### App ID

185407

### More Details

I can remove authorization checking based on the access token from my unsubscribe endpoint if this is the expected behaviour. I think all I'd need to do is add some sort of shared secret in the subscribeData that I echo back when unsubscribing.

**Comment by kola-er** [comment]
It is fixed now @misterjoshua. Thanks for your patience.
