### ISSUE TITLE
Publish new version for lodash vulnerability

### ISSUE THREAD

**Issue by camphillips22** [zapier/zapier-platform#78]
### Current Behavior
The `8.3.0` version has a dependency on `lodash` that fails `npm audit` checks.

### Desired Behavior
Publish a new version that fixes this dependency. 

I see that it was already fixed with #53 and #54, but I'm trying to build the code for a new integration into a larger code base and need the audit checks to pass.

**Comment by xavdid** [comment]
@camphillips22 which package specifically is this about?

**Comment by siers** [comment]
At least `zapier-platform-core` and `zapier-platform-cli`. I see the `package.json`s are updated, but still unpublished.

**Comment by xavdid** [comment]
Got it. I'm seeing a lot of noise in the `npm audit` results. We already allow arbitrary code execution (that's the whole point of the platform), so most of the security in core hasn't been as big of an issue. 

Is `lodash` the only one we need to bump? If you give me a full list we can make it happen.

**Comment by siers** [comment]
It was only lodash I think, but npm audit should show the right results. :)

**Comment by eliangcs** [comment]
This has been fixed in [8.4.2](https://github.com/zapier/zapier-platform/blob/master/CHANGELOG.md#842). Closing.
