### ISSUE TITLE
cli-app > bundle size 

### ISSUE THREAD

**Issue by B-Stefan** [zapier/zapier-platform#98]
Hi Zapier Team, 

the `zapier-platoform` has a hard limit of 6MB for cli-apps. This is nice to keep the upload process fast and the app in a maintainable size - 👍 nice engineered! We just hit that hard limit with our app and I investigated where all the space goes. 

<img width="882" alt="Screenshot 2019-11-13 at 11 06 22" src="https://user-images.githubusercontent.com/4060763/68753723-cb155f00-0605-11ea-9795-daf2f5e4194b.png">

It turns out that the `node_modules` folder is already 5MB and the biggest packages are `zapier-platform-core`  and `zapier-platform-schema` 

Is there any chance that we could tackle this issue. I have some ideas on how to avoid a big node_modules e.g: 

* Reduce size of `zapier-platform-core` and `zapier-platform-schema` by remove lodash 
* Remove `zapier-platform-core` as required dependency for every app (could be a dev-dep in my opinion?)
* Set the max bundle limit to 7 or 8 MB. 

What do you think about this? Is this an issue for other partners as well? 

Best Stefan

**Comment by B-Stefan** [comment]
Alternative idea: 
* Change lodash in `zapier-platform-core` and `zapier-platform-schema` to a peer dependency. This would save around 1.2MB

**Comment by xavdid** [comment]
hey @B-Stefan, thanks for writing in!

It's worth noting that the 6MB limit is applied against the zip. A freshly built zip using the `trigger` template weighs in at just under 2MB:

![](https://zappy.zapier.com/0813EEE4-A36F-4213-8B8B-9E623DB69EDD.png)

So while we could definitely slim `zapier-platform-core` down a little, there should still be plenty of space for your own code.

Can you tell us what dependencies you're using?

**Comment by B-Stefan** [comment]
Hey @xavdid

thanks for the super-fast response and you are totally right! I just upgraded the zapier-platform core from 8.3.0 to 8.4.2 and this reduced the bundle size by 1.3MB! Awesome job of the Zapier team 👍 ! 

Just to let you know our dependency list: 

```
    "@casecheck/api-schema": "private",
    "service-common": "private",
    "form-data": "^2.5.0",
    "json-to-graphql-query": "^1.9.0", --> arround 100k
    "lodash": "^4.17.11",
    "request": "2.88.0",
    "zapier-platform-core": "8.4.2",
    "zapier-platform-json-schema": "0.4.4" --> arround 100k
```

I'm pretty sure that the `request` dependency causes a lot of nested dependencies. If I have time I  try to replace `request` by some other library to perform file uploads. 

Thanks again for the help and sorry to bother you! I totally forgot to upgrade the platform.
